version: "3.9"

services:
  shoes-market-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shoes-market-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env